apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: httpd-deploy
  name: httpd-service
  namespace: xfusion
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: httpd-deploy
  type: NodePort
status:
  loadBalancer: {}
