apiVersion: v1
kind: Pod
metadata:
  name: volume-sharing
spec:
  containers:
  - image: debian:latest
    name: azfar-vol1
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /tmp/azfar123/
      name: shared-vol
  - image: debian:latest
    name: abrar-vol2
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /tmp/abrar123/
      name: shared-vol
  volumes:
  - name: shared-vol
    emptyDir:

