apiVersion: v1
kind: Service
metadata:
  name: web-nautilus
  labels:
    app: nginx  # Ensure this label is present
spec:
  selector:
    app: nginx  # Ensure the selector matches the pod's label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009
  type: NodePort
