apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: lemp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30005
  selector:
    app: lemp
  type: NodePort
status:
  loadBalancer: {}
