apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mysql-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: lemp
  type: ClusterIP
status:
  loadBalancer: {}
